# Book settings
title: Intermediate Python for Humanists
author: William J.B. Mattingly
# logo: ''
execute:
  execute_notebooks: 'off'
parse:
  myst_extended_syntax: true
# Information about where the book exists on the web
repository:
  url: https://github.com/wjbmattingly/intermediate-python-for-dh
  branch: main
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
launch_buttons:
  colab_url: "https://colab.research.google.com"
